### PR TITLE
Allocating response buffer based on body size and on header size when…

### LINKED ISSUE #54: The techempower example crashes for longer messages
Hi,

I tried compiling the techempower benchmarks with the following patch:

```diff
(temp-python)[jlouis@daemonette Haywire]$ git diff
diff --git a/src/samples/techempower_benchmark/program.c b/src/samples/techempower_benchmark/program.c
index e0db9c8..41901ac 100644
--- a/src/samples/techempower_benchmark/program.c
+++ b/src/samples/techempower_benchmark/program.c
@@ -26,7 +26,7 @@ void get_plaintext(http_request* request, hw_http_response* response, void* user
     SETSTRING(content_type_value, "text/plain");
     hw_set_response_header(response, &content_type_name, &content_type_value);
     
-    SETSTRING(body, "Hello, World!");
+    SETSTRING(body, "CHAPTER I. Down the Rabbit-Hole  Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, <and what is the use of a book,> thought Alice <without pictures or conversations?> So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her. There was nothing so very remarkable in that; nor did Alice think it so very much out of the way to hear the Rabbit say to itself, <Oh dear! Oh dear! I shall be late!> (when she thought it over afterwards, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural); but when the Rabbit actually took a watch out of its waistcoat-pocket, and looked at it, and then hurried on, Alice started to her feet, for it flashed across her mind that she had never before seen a rabbit with either a waistcoat-pocket, or a watch to take out of it, and burning with curiosity, she ran across the field after it, and fortunately was just in time to see it pop down a large rabbit-hole under the hedge. In another moment down went Alice after it, never once considering how in the world she was to get out again. The rabbit-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep well. Either the well was very deep, or she fell very slowly, for she had plenty of time as she went down to look about her and to wonder what was going to happen next. First, she tried to look down and make out what she was coming to, but it was too dark to see anything; then she looked at the sides of the well, and noticed that they were filled with cupboards......");
     hw_set_body(response, &body);
     
     if (request->keep_alive)
```

And then a single curl against the `/plaintext` endpoint results in:

```
*** Error in `./builds/unix/release/techempower_benchmark': double free or corruption (!prev): 0x00007
f5d34013f00 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x7198e)[0x7f5df90a698e]
/usr/lib/libc.so.6(+0x76dee)[0x7f5df90abdee]
/usr/lib/libc.so.6(+0x775cb)[0x7f5df90ac5cb]
./builds/unix/release/techempower_benchmark[0x405dbc]
./builds/unix/release/techempower_benchmark[0x410b8a]
./builds/unix/release/techempower_benchmark[0x411511]
./builds/unix/release/techempower_benchmark[0x40cd93]
./builds/unix/release/techempower_benchmark[0x4076ee]
./builds/unix/release/techempower_benchmark[0x412b47]
```

I had expected the first 2053 bytes of Alice in Wonderland to magically come out of the woodwork, and it also does. Curl returns it correctly. But haywire crashes with the above abort right after.

I also tried a really hacked solution where I used `create_string` to heap-allocate the string and refer to it as a global value because I had a hunch it was due to some stack allocation trouble. But it still fails with the above error.

This is on an ArchLinux, which is fairly recent. Can anyone reproduce this one on other architectures?

### PR DESCRIPTION
**Pull request by nmdguerreiro**
… required and not just statically. Fixes #54.

By default, it will allocate 1K for the headers, but it will reallocate as necessary if the headers take more than 1k.

Since dynamic allocation only kicks in if required, performance is equivalent with the previous version, as the only difference is allocating enough memory to hold the entire body.

### Performance of previous version
```
[ec2-user@ip-172-31-31-0 wrk]$ ./wrk --latency -d 10s -t 8 -c 128 http://172.31.16.12:8000
Running 10s test @ http://172.31.16.12:8000
  8 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   360.21us  305.93us  21.32ms   94.34%
    Req/Sec    47.47k     3.76k   54.69k    53.47%
  Latency Distribution
     50%  294.00us
     75%  369.00us
     90%  506.00us
     99%    1.47ms
  3815801 requests in 10.10s, 574.97MB read
Requests/sec: 377799.31
Transfer/sec:     56.93MB
```

### Performance of this commit
```
[ec2-user@ip-172-31-31-0 wrk]$ ./wrk --latency -d 10s -t 8 -c 128 http://172.31.16.12:8000
Running 10s test @ http://172.31.16.12:8000
  8 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   367.45us  501.67us  40.67ms   96.27%
    Req/Sec    47.62k     2.41k   54.16k    85.52%
  Latency Distribution
     50%  292.00us
     75%  364.00us
     90%  494.00us
     99%    1.64ms
  3827749 requests in 10.10s, 576.45MB read
Requests/sec: 379006.36
Transfer/sec:     57.08MB
```

Also, just proof that this fixes #54:
```
[ec2-user@ip-172-31-31-0 wrk]$ curl http://172.31.16.12:8000
CHAPTER I. Down the Rabbit-Hole  Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, <and what is the use of a book,> thought Alice <without pictures or conversations?> So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her. There was nothing so very remarkable in that; nor did Alice think it so very much out of the way to hear the Rabbit say to itself, <Oh dear! Oh dear! I shall be late!> (when she thought it over afterwards, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural); but when the Rabbit actually took a watch out of its waistcoat-pocket, and looked at it, and then hurried on, Alice started to her feet, for it flashed across her mind that she had never before seen a rabbit with either a waistcoat-pocket, or a watch to take out of it, and burning with curiosity, she ran across the field after it, and fortunately was just in time to see it pop down a large rabbit-hole under the hedge. In another moment down went Alice after it, never once considering how in the world she was to get out again. The rabbit-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep well. Either the well was very deep, or she fell very slowly, for she had plenty of time as she went down to look about her and to wonder what was going to happen next. First, she tried to look down and make out what she was coming to, but it was too dark to see anything; then she looked at the sides of the well, and noticed that they were filled with cupboards......
```

### CODE REVIEW

**Comment by kellabyte** [comment]
Oh my god you're the best. I've been wanting to get this complete for ages! Thank you so very much to contributing to Haywire. I really do appreciate the help :) I'm going to try and review this in the next couple days and test it and merge it!

**Comment by nmdguerreiro** [comment]
Happy to help as I'll be benefiting from all the work put into this project :grin:

**Comment by nmdguerreiro** [comment]
Got rid of the dependency on the math lib. It's faster to count the number of characters by diving iteratively than using log10.

**Comment by kellabyte** [comment]
I just did benchmarks in my benchmark environment and it does look like we lost some performance in this implementation. We are losing around `500,000 to 700,000 requests/second`. I ran the benchmark enough times to make sure this wasn't benchmark/environment blips and anomalies. I wonder if it's the `num_chars` or `calloc` calls?

### Before
```
../bin/wrk/wrk --script ./pipelined_get.lua --latency -d 30s -t 40 -c 512 http://server:8000/foo/bar -- 32

Running 30s test @ http://server:8000/foo/bar
  40 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.49ms    3.08ms 145.65ms   88.15%
    Req/Sec   226.94k    43.37k  438.40k    85.31%
  Latency Distribution
     50%    0.88ms
     75%    1.50ms
     90%    6.97ms
     99%    0.00us
  271130610 requests in 30.10s, 39.89GB read
Requests/sec: 9008388.12
Transfer/sec:      1.33GB
```


### After
```
../bin/wrk/wrk --script ./pipelined_get.lua --latency -d 30s -t 40 -c 512 http://server:8000/foo/bar -- 32

Running 30s test @ http://server:8000/foo/bar
  40 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.00ms    3.35ms  97.72ms   85.18%
    Req/Sec   210.50k    58.23k  422.88k    72.83%
  Latency Distribution
     50%    0.98ms
     75%    1.97ms
     90%    9.33ms
     99%    0.00us
  251246262 requests in 30.10s, 36.97GB read
Requests/sec: 8347135.09
Transfer/sec:      1.23GB
```

**Comment by nmdguerreiro** [comment]
I'll have a look. I think it must be `calloc` call. I'll try `malloc` and null terminating the string, as we don't really need the memory block to be set to 0s. I'll also make sure I run the benchmarks before PR from now on. Worth creating a PR guidelines doc (e.g. run benchmarks)?

**Comment by nmdguerreiro** [comment]
I replaced calloc with malloc but I was still seeing about 20% less requests being served than with the previous version.

I instrumented the code like so, to count the number of CPU cycles used:

```c
inline uint64_t rdtsc() {
    uint32_t lo, hi;
    __asm__ __volatile__ (
      "xorl %%eax, %%eax\n"
      "cpuid\n"
      "rdtsc\n"
      : "=a" (lo), "=d" (hi)
      :
      : "%ebx", "%ecx");
    return (uint64_t)hi << 32 | lo;
}

hw_string* create_response_buffer(hw_http_response* response)
{
    unsigned long long before = rdtsc();
    http_response* resp = (http_response*)response;
    hw_string* response_string = malloc(sizeof(hw_string));
    printf("Alloc hw_string: %lld\n", (rdtsc() - before));
    before = rdtsc();
    hw_string* cached_entry = get_cached_request(resp->status_code.value);
    printf("Get cached request: %lld\n", (rdtsc() - before));
    before = rdtsc();
    hw_string content_length;

    int i = 0;

    char length_header[] = "Content-Length: ";
    int line_sep_size = sizeof(CRLF);

    int header_buffer_incr = 1024;
    int body_size = resp->body.length + line_sep_size;
    int header_size_remaining = header_buffer_incr;
    int response_size = header_size_remaining + sizeof(length_header) + num_chars(resp->body.length) + 2 * line_sep_size + body_size + line_sep_size;
    
    printf("Sizing: %lld\n", (rdtsc() - before));
    before = rdtsc();

    response_string->value = malloc(response_size + 1);
    
    printf("Alloc body value: %lld\n", (rdtsc() - before));
    before = rdtsc();

    response_string->length = 0;
    append_string(response_string, cached_entry);
    printf("Write cached entry: %lld\n", (rdtsc() - before));
    before = rdtsc();
    
    for (i=0; i< resp->number_of_headers; i++)
    {
        http_header header = resp->headers[i];

        header_size_remaining -= strlen(header.name.value) + 2 + strlen(header.value.value) + line_sep_size;
        if (header_size_remaining < 0) {
            header_size_remaining += header_buffer_incr * ((-header_size_remaining/header_buffer_incr) + 1);
            response_size += header_size_remaining;
            response_string->value = realloc(response_string->value, response_size + 1);
        }

        append_string(response_string, &header.name);
        APPENDSTRING(response_string, ": ");
        append_string(response_string, &header.value);
        APPENDSTRING(response_string, CRLF);
    }
    
    printf("Write headers: %lld\n", (rdtsc() - before));
    before = rdtsc();
    
    /* Add the body */
    APPENDSTRING(response_string, length_header);

    string_from_int(&content_length, body_size, 10);
    
    append_string(response_string, &content_length);
    APPENDSTRING(response_string, CRLF CRLF);
    printf("Write content length: %lld\n", (rdtsc() - before));
    before = rdtsc();
    
    if (resp->body.length > 0)
    {
        append_string(response_string, &resp->body);
    }
    APPENDSTRING(response_string, CRLF);
    response_string->value[response_string->length] = '\0';
    printf("Write body: %lld\n", (rdtsc() - before));
    before = rdtsc();
    
    return response_string;
}

```

And the output is: 
```
Alloc hw_string: 300
Get cached request: 1494953
Sizing: 384
Alloc body value: 1034
Write cached entry: 244
Write headers: 778
Write content length: 450
Write body: 175
```

As you can see, getting a cached request takes a lot longer than anything else and effectively dwarfs the time spent appending the body and headers.

I also instrumented the previous version of the code (e9924a7dacbc1a93c0d656638348952ccd1f2e64), and got the following results: 

```
Alloc hw_string: 264
Get cached request: 1517278
Alloc static: 1216
Write cached entry: 476
Write headers: 544
Write content length: 484
Write body: 188
```

The instrumented code for the previous version is as follows:
```c
inline uint64_t rdtsc() {
    uint32_t lo, hi;
    __asm__ __volatile__ (
                          "xorl %%eax, %%eax\n"
                          "cpuid\n"
                          "rdtsc\n"
                          : "=a" (lo), "=d" (hi)
                          :
                          : "%ebx", "%ecx");
    return (uint64_t)hi << 32 | lo;
}

hw_string* create_response_buffer(hw_http_response* response)
{
    unsigned long long before = rdtsc();
    http_response* resp = (http_response*)response;
    hw_string* response_string = malloc(sizeof(hw_string));
    printf("Alloc hw_string: %lld\n", (rdtsc() - before));
    before = rdtsc();
    hw_string* cached_entry = get_cached_request(resp->status_code.value);
    printf("Get cached request: %lld\n", (rdtsc() - before));
    before = rdtsc();
    hw_string content_length;

    int i = 0;

    response_string->value = calloc(1024, 1);
    response_string->length = 0;
    printf("Alloc static: %lld\n", (rdtsc() - before));
    before = rdtsc();
    
    append_string(response_string, cached_entry);
    printf("Write cached entry: %lld\n", (rdtsc() - before));
    before = rdtsc();
    
    for (i=0; i< resp->number_of_headers; i++)
    {
        http_header header = resp->headers[i];
        append_string(response_string, &header.name);
        APPENDSTRING(response_string, ": ");
        append_string(response_string, &header.value);
        APPENDSTRING(response_string, CRLF);
    }
    
    printf("Write headers: %lld\n", (rdtsc() - before));
    before = rdtsc();

    
    /* Add the body */
    APPENDSTRING(response_string, "Content-Length: ");
    
    string_from_int(&content_length, resp->body.length + 3, 10);
    append_string(response_string, &content_length);
    APPENDSTRING(response_string, CRLF CRLF);
    
    printf("Write content length: %lld\n", (rdtsc() - before));
    before = rdtsc();

    if (resp->body.length > 0)
    {
        append_string(response_string, &resp->body);
    }
    APPENDSTRING(response_string, CRLF);
    
    printf("Write body: %lld\n", (rdtsc() - before));
    before = rdtsc();
    return response_string;
}

``` 

The number of CPU cycles seems pretty much the same to me, and it's actually higher on the old version of the code: 1498318 in the new version, 1519906 in the old version.

I suspect that the problem is to do with the fact that I'm now allocating 1Kb + body size, as opposed to just 1Kb that was allocated before, causing memory access to take longer. So I allocated 512 bytes instead et voilá:

```
Running 10s test @ http://localhost:8000/
  40 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   126.54ms   95.71ms 641.56ms   70.58%
    Req/Sec     1.85k     1.79k    8.24k    82.40%
  Latency Distribution
     50%  103.09ms
     75%  184.48ms
     90%  256.62ms
     99%  424.43ms
  490179 requests in 10.09s, 73.86MB read
  Socket errors: connect 0, read 313, write 0, timeout 0
Requests/sec:  48564.76
Transfer/sec:      7.32MB
```

For your reference, here are the results of building with commit ge9924a7 (that allocated 1k for headers and body):

```
Running 10s test @ http://localhost:8000/
  40 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   119.69ms   88.39ms 559.05ms   72.26%
    Req/Sec     1.70k     1.47k   11.52k    77.06%
  Latency Distribution
     50%   96.89ms
     75%  167.64ms
     90%  242.38ms
     99%  396.18ms
  470237 requests in 10.09s, 70.86MB read
  Socket errors: connect 0, read 296, write 0, timeout 0
Requests/sec:  46584.09
Transfer/sec:      7.02MB
```

I'll change the latest changes to my branch.

PS: I had to run the benchmarks a few times and selected the best results for each of the commits, as I get a lot of variance on my laptop (e.g. 39.6k RPS vs 54.8k RPS with the same code).

**Comment by kellabyte** [comment]
I'm still seeing the same results. Here's `valgrind callgraph` results.

### Before
```
--------------------------------------------------------------------------------
         Ir
--------------------------------------------------------------------------------
884,736,669  PROGRAM TOTALS

--------------------------------------------------------------------------------
         Ir  file:function
--------------------------------------------------------------------------------
192,555,889  /build/buildd/glibc-2.21/malloc/malloc.c:_int_malloc [/lib/x86_64-linux-gnu/libc-2.21.so]
128,123,967  /build/buildd/glibc-2.21/malloc/malloc.c:_int_free [/lib/x86_64-linux-gnu/libc-2.21.so]
 58,857,791  /build/buildd/glibc-2.21/malloc/malloc.c:malloc [/lib/x86_64-linux-gnu/libc-2.21.so]
 54,076,426  /build/buildd/glibc-2.21/malloc/malloc.c:free [/lib/x86_64-linux-gnu/libc-2.21.so]
 41,650,063  /build/buildd/glibc-2.21/malloc/malloc.c:malloc_consolidate [/lib/x86_64-linux-gnu/libc-2.21.so]
 37,866,240  src/haywire/http_response.c:create_response_buffer [/root/tmp3/haywire/build/hello_world]
 37,024,768  src/haywire/picohttpparser.c:phr_parse_request [/root/tmp3/haywire/build/hello_world]
 32,169,213  /build/buildd/glibc-2.21/string/../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:__memcpy_sse2_unaligned [/lib/x86_64-linux-gnu/libc-2.21.so]
 28,248,478  src/haywire/picohttpparser.c:get_token_to_eol [/root/tmp3/haywire/build/hello_world]
 24,192,320  src/haywire/picohttpparser.c:parse_headers [/root/tmp3/haywire/build/hello_world]
 23,111,809  src/haywire/khash.h:get_cached_request
 22,719,744  src/haywire/http_request.c:http_request_complete_request [/root/tmp3/haywire/build/hello_world]
 19,914,683  /build/buildd/glibc-2.21/malloc/malloc.c:calloc [/lib/x86_64-linux-gnu/libc-2.21.so]
 19,163,105  src/haywire/hw_string.c:append_string [/root/tmp3/haywire/build/hello_world]
 18,297,489  src/haywire/http_response_cache.c:get_cached_request [/root/tmp3/haywire/build/hello_world]
 13,553,364  /build/buildd/glibc-2.21/string/../sysdeps/x86_64/strlen.S:strlen [/lib/x86_64-linux-gnu/libc-2.21.so]
 10,308,032  src/samples/hello_world/program.c:get_root [/root/tmp3/haywire/build/hello_world]
  9,887,300  src/haywire/route_compare_method.c:hw_route_compare_method [/root/tmp3/haywire/build/hello_world]
  9,676,928  src/haywire/http_response.c:hw_set_response_header [/root/tmp3/haywire/build/hello_world]
  8,825,206  /build/buildd/glibc-2.21/string/../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:__strcmp_sse2_unaligned [/lib/x86_64-linux-gnu/libc-2.21.so]
  8,289,814  src/haywire/http_server.c:http_server_write_response_batched [/root/tmp3/haywire/build/hello_world]
  8,204,352  src/haywire/hw_string.c:string_from_int [/root/tmp3/haywire/build/hello_world]
  7,362,880  src/haywire/http_request.c:free_http_request [/root/tmp3/haywire/build/hello_world]
  7,251,442  src/haywire/http_server.c:http_stream_on_read_pico [/root/tmp3/haywire/build/hello_world]
  6,942,144  src/haywire/http_request.c:hw_http_response_send [/root/tmp3/haywire/build/hello_world]
  5,896,340  /usr/include/x86_64-linux-gnu/bits/string3.h:append_string
  5,890,304  src/haywire/http_request.c:create_http_request [/root/tmp3/haywire/build/hello_world]
  5,679,936  /usr/include/x86_64-linux-gnu/bits/string2.h:hw_route_compare_method
  4,865,846  lib/libuv/src/unix/stream.c:uv__write [/root/tmp3/haywire/build/hello_world]
  4,628,096  /build/buildd/glibc-2.21/debug/../sysdeps/x86_64/strcpy_chk.S:__strcpy_chk [/lib/x86_64-linux-gnu/libc-2.21.so]
  3,586,408  /build/buildd/glibc-2.21/nptl/pthread_getspecific.c:pthread_getspecific [/lib/x86_64-linux-gnu/libpthread-2.21.so]
  3,576,256  /build/buildd/glibc-2.21/string/../sysdeps/x86_64/multiarch/strcmp-sse42.S:__strncasecmp_avx [/lib/x86_64-linux-gnu/libc-2.21.so]
  3,155,520  src/haywire/http_response.c:hw_create_http_response [/root/tmp3/haywire/build/hello_world]
  3,155,520  /usr/include/x86_64-linux-gnu/bits/string3.h:create_response_buffer
  1,801,796  lib/libuv/src/uv-common.c:uv__count_bufs [/root/tmp3/haywire/build/hello_world]
  1,051,840  src/haywire/http_response.c:hw_set_response_status_code [/root/tmp3/haywire/build/hello_world]
  1,051,840  src/haywire/http_response.c:hw_set_body [/root/tmp3/haywire/build/hello_world]
    841,476  /usr/include/x86_64-linux-gnu/bits/string3.h:hw_route_compare_method
    767,756  /build/buildd/glibc-2.21/stdio-common/vfprintf.c:vfprintf [/lib/x86_64-linux-gnu/libc-2.21.so]
```

### After
```
--------------------------------------------------------------------------------
         Ir
--------------------------------------------------------------------------------
881,825,176  PROGRAM TOTALS

--------------------------------------------------------------------------------
         Ir  file:function
--------------------------------------------------------------------------------
192,825,337  /build/buildd/glibc-2.21/malloc/malloc.c:_int_malloc [/lib/x86_64-linux-gnu/libc-2.21.so]
127,466,255  /build/buildd/glibc-2.21/malloc/malloc.c:_int_free [/lib/x86_64-linux-gnu/libc-2.21.so]
 58,566,335  /build/buildd/glibc-2.21/malloc/malloc.c:malloc [/lib/x86_64-linux-gnu/libc-2.21.so]
 53,808,653  /build/buildd/glibc-2.21/malloc/malloc.c:free [/lib/x86_64-linux-gnu/libc-2.21.so]
 41,484,514  /build/buildd/glibc-2.21/malloc/malloc.c:malloc_consolidate [/lib/x86_64-linux-gnu/libc-2.21.so]
 37,676,160  src/haywire/http_response.c:create_response_buffer [/root/tmp3/haywire/build/hello_world]
 36,838,912  src/haywire/picohttpparser.c:phr_parse_request [/root/tmp3/haywire/build/hello_world]
 32,007,084  /build/buildd/glibc-2.21/string/../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:__memcpy_sse2_unaligned [/lib/x86_64-linux-gnu/libc-2.21.so]
 28,106,677  src/haywire/picohttpparser.c:get_token_to_eol [/root/tmp3/haywire/build/hello_world]
 24,070,880  src/haywire/picohttpparser.c:parse_headers [/root/tmp3/haywire/build/hello_world]
 22,995,022  src/haywire/khash.h:get_cached_request
 22,605,696  src/haywire/http_request.c:http_request_complete_request [/root/tmp3/haywire/build/hello_world]
 19,817,298  /build/buildd/glibc-2.21/malloc/malloc.c:calloc [/lib/x86_64-linux-gnu/libc-2.21.so]
 19,067,438  src/haywire/hw_string.c:append_string [/root/tmp3/haywire/build/hello_world]
 18,205,518  src/haywire/http_response_cache.c:get_cached_request [/root/tmp3/haywire/build/hello_world]
 13,471,290  /build/buildd/glibc-2.21/string/../sysdeps/x86_64/strlen.S:strlen [/lib/x86_64-linux-gnu/libc-2.21.so]
 10,256,288  src/samples/hello_world/program.c:get_root [/root/tmp3/haywire/build/hello_world]
  9,837,668  src/haywire/route_compare_method.c:hw_route_compare_method [/root/tmp3/haywire/build/hello_world]
  9,628,352  src/haywire/http_response.c:hw_set_response_header [/root/tmp3/haywire/build/hello_world]
  8,780,623  /build/buildd/glibc-2.21/string/../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:__strcmp_sse2_unaligned [/lib/x86_64-linux-gnu/libc-2.21.so]
  8,248,201  src/haywire/http_server.c:http_server_write_response_batched [/root/tmp3/haywire/build/hello_world]
  8,163,168  src/haywire/hw_string.c:string_from_int [/root/tmp3/haywire/build/hello_world]
  7,325,920  src/haywire/http_request.c:free_http_request [/root/tmp3/haywire/build/hello_world]
  7,215,109  src/haywire/http_server.c:http_stream_on_read_pico [/root/tmp3/haywire/build/hello_world]
  6,907,296  src/haywire/http_request.c:hw_http_response_send [/root/tmp3/haywire/build/hello_world]
  5,866,904  /usr/include/x86_64-linux-gnu/bits/string3.h:append_string
  5,860,736  src/haywire/http_request.c:create_http_request [/root/tmp3/haywire/build/hello_world]
  5,651,424  /usr/include/x86_64-linux-gnu/bits/string2.h:hw_route_compare_method
  4,841,525  lib/libuv/src/unix/stream.c:uv__write [/root/tmp3/haywire/build/hello_world]
  4,604,864  /build/buildd/glibc-2.21/debug/../sysdeps/x86_64/strcpy_chk.S:__strcpy_chk [/lib/x86_64-linux-gnu/libc-2.21.so]
  3,573,508  /build/buildd/glibc-2.21/nptl/pthread_getspecific.c:pthread_getspecific [/lib/x86_64-linux-gnu/libpthread-2.21.so]
  3,558,304  /build/buildd/glibc-2.21/string/../sysdeps/x86_64/multiarch/strcmp-sse42.S:__strncasecmp_avx [/lib/x86_64-linux-gnu/libc-2.21.so]
  3,139,680  src/haywire/http_response.c:hw_create_http_response [/root/tmp3/haywire/build/hello_world]
  3,139,680  /usr/include/x86_64-linux-gnu/bits/string3.h:create_response_buffer
  1,792,754  lib/libuv/src/uv-common.c:uv__count_bufs [/root/tmp3/haywire/build/hello_world]
  1,046,560  src/haywire/http_response.c:hw_set_body [/root/tmp3/haywire/build/hello_world]
  1,046,560  src/haywire/http_response.c:hw_set_response_status_code [/root/tmp3/haywire/build/hello_world]
    837,252  /usr/include/x86_64-linux-gnu/bits/string3.h:hw_route_compare_method
    781,436  /build/buildd/glibc-2.21/stdio-common/vfprintf.c:vfprintf [/lib/x86_64-linux-gnu/libc-2.21.so]
```

You're right, the instruction counts aren't much different so it must still be memory access?

**Comment by kellabyte** [comment]
I did a `printf("%d\n", response_size);` and it's reporting `554` so we are allocating un-aligned memory. I wonder if we will get our boost back if we pad with aligned memory sizes?

**Comment by nmdguerreiro** [comment]
Running previous master commit vs my changes:

```
[ec2-user@ip-172-31-31-0 ~]$ ~/wrk/wrk --script pipelined_get.lua --latency -d 10s -t 40 -c 512 http://172.31.16.12:8000 -- 32
Running 10s test @ http://172.31.16.12:8000
  40 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    21.14ms   11.53ms 119.08ms   58.39%
    Req/Sec     9.58k     1.35k   11.64k    61.48%
  Latency Distribution
     50%   21.02ms
     75%   30.58ms
     90%   37.10ms
     99%   40.02ms
  3829208 requests in 10.10s, 576.52MB read
Requests/sec: 379102.18
Transfer/sec:     57.08MB
[ec2-user@ip-172-31-31-0 ~]$ ~/wrk/wrk --script pipelined_get.lua --latency -d 10s -t 40 -c 512 http://172.31.16.12:8000 -- 32
Running 10s test @ http://172.31.16.12:8000
  40 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    21.21ms   11.50ms 121.14ms   58.37%
    Req/Sec     9.60k     1.16k   11.64k    66.22%
  Latency Distribution
     50%   21.09ms
     75%   30.60ms
     90%   37.11ms
     99%   40.01ms
  3842251 requests in 10.10s, 578.93MB read
Requests/sec: 380410.65
Transfer/sec:     57.32MB
```

I get very similar results :cry:

**Comment by kellabyte** [comment]
Yeah I just did another test and there's about a 100MB/s difference even if I set `470` bytes as the buffer default size so that when your calculation does its work it results in `512` which should be aligned I still get a performance drop.

### Before
```
../bin/wrk/wrk --script ./pipelined_get.lua --latency -d 60s -t 40 -c 760 http://server:8000 -- 32

Running 1m test @ http://server:8000
  40 threads and 760 connections
^C  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.70ms    2.63ms 202.77ms   89.23%
    Req/Sec   233.03k    41.34k  447.68k    89.26%
  Latency Distribution
     50%    1.18ms
     75%    1.89ms
     90%    5.03ms
     99%    0.00us
  139138752 requests in 15.04s, 20.47GB read
Requests/sec: 9252834.06
Transfer/sec:      1.36GB
```

### After
```
../bin/wrk/wrk --script ./pipelined_get.lua --latency -d 10s -t 40 -c 760 http://server:8000 -- 32

Running 10s test @ http://server:8000
  40 threads and 760 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.32ms    3.98ms 218.89ms   89.95%
    Req/Sec   212.97k    61.57k  454.95k    74.06%
  Latency Distribution
     50%    1.45ms
     75%    2.56ms
     90%    6.34ms
     99%    0.00us
  85016768 requests in 10.10s, 12.51GB read
Requests/sec: 8417482.61
Transfer/sec:      1.24GB
```

File: src/haywire/http_response.c [hunk 1]
```diff
@@ -66,13 +78,30 @@ hw_string* create_response_buffer(hw_http_response* response)
...
+    response_string->value = malloc(response_size);
+
     response_string->length = 0;
     append_string(response_string, cached_entry);
     
     for (i=0; i< resp->number_of_headers; i++)
     {
         http_header header = resp->headers[i];
+
+        header_size_remaining -= strlen(header.name.value) + 2 + strlen(header.value.value) + line_sep_size;
```
Comment (kellabyte) [inline src/haywire/http_response.c]: Change the `strlen(header.name.value)` to `header.name.length` and change `strlen(header.value.value)` to `header.value.length`. Haywire has `hw_string` that has pre-set lengths so that we can avoid string loops inside Haywire. This was a big gain in performance as we avoid looping buffers as much as possible :)

Making this change gave me the following.

```
../bin/wrk/wrk --script ./pipelined_get.lua --latency -d 10s -t 40 -c 760 http://server:8000 -- 32
Running 10s test @ http://server:8000
  40 threads and 760 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.92ms    4.10ms 206.24ms   91.91%
    Req/Sec   234.34k    38.82k  445.76k    85.05%
  Latency Distribution
     50%    1.24ms
     75%    1.95ms
     90%    4.10ms
     99%    0.00us
  93564882 requests in 10.10s, 13.76GB read
Requests/sec: 9264711.05
Transfer/sec:      1.36GB
```

Next we should test unaligned vs aligned buffer sizes but this is looking very promising. We got dynamic buffer sizes without losing noticeable performance :)

**Comment by nmdguerreiro** [comment]
Good news!

I ran the benchmark with the batching and pico parser enabled and there aren't significant performance differences introduced by my changes even with a 512 byte allocation.

Results:

### picohttpparser branch
```
[ec2-user@ip-172-31-31-0 ~]$ ~/wrk/wrk --script pipelined_get.lua --latency -d 10s -t 40 -c 512 http://172.31.16.12:8000 -- 64
Running 10s test @ http://172.31.16.12:8000
  40 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    97.50ms  188.80ms   1.82s    84.60%
    Req/Sec    43.88k    27.21k  278.87k    92.48%
  Latency Distribution
     50%    9.06ms
     75%  147.43ms
     90%  405.80ms
     99%    0.00us
  17256544 requests in 10.10s, 2.54GB read
  Socket errors: connect 0, read 0, write 0, timeout 4
Requests/sec: 1708620.65
Transfer/sec:    257.46MB
```

### picohttpparser branch + commits 8e2c3787695076ee967a3013075dcbeae76eedc6 f1a7e03c08463a37398817391312540cd162804d e624d74de0e7271e505ec99133b792ae43653c0a and 142458fd2c24cd9a6c60909b4dc80d4a7171e870
```
[ec2-user@ip-172-31-31-0 ~]$ ~/wrk/wrk --script pipelined_get.lua --latency -d 10s -t 40 -c 512 http://172.31.16.12:8000 -- 64
Running 10s test @ http://172.31.16.12:8000
  40 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   104.47ms  196.21ms   1.85s    85.06%
    Req/Sec    43.28k    26.17k  275.84k    92.89%
  Latency Distribution
     50%    9.33ms
     75%  158.21ms
     90%  403.34ms
     99%    0.00us
  17214072 requests in 10.10s, 2.53GB read
  Socket errors: connect 0, read 0, write 0, timeout 3
Requests/sec: 1704322.22
Transfer/sec:    256.68MB
```

**Comment by nmdguerreiro** [comment]
@kellabyte happy to merge this or do you want to wait for pico parser to be merged first?

**Comment by kellabyte** [comment]
I'm okay with merging it before pico parser. I just was verifying performance by using the two together. Let me run one more benchmark to verify your results in the next couple days (I hope) and I'll merge :) Thanks so much for this!
